target 'YMNetworkActivityManager', :exclusive => true do
  pod "YMNetworkActivityManager", :path => "../"
end

target 'Tests', :exclusive => true do
  pod "YMNetworkActivityManager", :path => "../"
end
