language: objective-c
before_install:
- cd Example && pod install && cd -
- gem install xcpretty
script:
- xcodebuild -workspace Example/YMNetworkActivityManager.xcworkspace -scheme YMNetworkActivityManagerShared -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO test | xcpretty -c; exit ${PIPESTATUS[0]}
